<?xml version="1.0"?>
<package format="3">
  <name>fkie_iop_wireshark_plugin</name>
  <version>1.0.0</version>
  <description>Wireshark dissector for IOP</description>

  <author email="lukas.boes@fkie.fraunhofer.de">Lukas Boes</author>
  <author email="alexander.tiderko@fkie.fraunhofer.de">Alexander Tiderko</author>
  <maintainer email="alexander.tiderko@fkie.fraunhofer.de">Alexander Tiderko</maintainer>
  <license>MIT</license>

  <buildtool_depend condition="$ROS_VERSION == 1">catkin</buildtool_depend>
  <buildtool_depend condition="$ROS_VERSION == 2">ament_cmake</buildtool_depend>

  <!-- <depend>python-pyxb</depend> -->

  <export>
    <build_type condition="$ROS_VERSION == 1">catkin</build_type>
    <build_type condition="$ROS_VERSION == 2">ament_cmake</build_type>
  </export>
</package>
